use crate::plugins::applications::DesktopEntry;
use anyhow::anyhow;
use std::ffi::OsString;
use std::mem::MaybeUninit;
use std::os::windows::ffi::OsStringExt;
use windows::core::*;
use windows::Win32::Foundation::{S_FALSE, S_OK};
use windows::Win32::System::Com::*;
use windows::Win32::System::SystemServices::*;
use windows::Win32::UI::Shell::Common::*;
use windows::Win32::UI::Shell::*;
use windows::Win32::UI::WindowsAndMessaging::*;

pub fn get_apps() -> Vec<DesktopEntry> {
    run_test().unwrap()
}

fn run_test() -> anyhow::Result<Vec<DesktopEntry>> {
    // SAFETY: no idea, I hope somebody reviews this
    unsafe {
        let hresult = CoInitializeEx(None, COINIT_APARTMENTTHREADED);
        if hresult != S_OK {
            return Err(anyhow!("CoInitializeEx {:X}", hresult.0));
        }

        let collect_fn = || {
            let apps_folder = SHGetKnownFolderItem::<_, IShellItem2>(&FOLDERID_AppsFolder, KF_FLAG_DEFAULT, None)
                .map_err(|err| anyhow!("SHGetKnownFolderItem {}", err))?;

            let shell_folder = apps_folder.BindToHandler::<_, IShellFolder2>(None, &BHID_SFObject)
                .map_err(|err| anyhow!("BindToHandler {}", err))?;

            let mut enum_items: Option<IEnumIDList> = None;

            let hresult = shell_folder.EnumObjects(None, SHCONTF_NONFOLDERS.0 as u32, &mut enum_items);
            if hresult != S_OK {
                return Err(anyhow!("EnumObjects {:X}", hresult.0));
            }

            let enum_items = enum_items.ok_or(anyhow!("EnumObjects None"))?;

            let mut items: [*mut ITEMIDLIST; 1] = [&mut ITEMIDLIST::default()];
            let mut result = vec![];

            loop {
                let hresult = enum_items.Next(&mut items, None);
                if hresult == S_FALSE {
                    break;
                }

                if hresult != S_OK {
                    return Err(anyhow!("Next {:X}", hresult.0));
                }

                let [item] = items;

                let name = get_display_name(&shell_folder, item, SHGDN_NORMAL)?
                    .into_string()
                    .unwrap();

                let id = get_display_name(&shell_folder, item, SHGDNF(SHGDN_FORPARSING.0 | SHGDN_INFOLDER.0))?
                    .into_string()
                    .unwrap();

                // let hidden = get_attribute(&shell_folder, item, SFGAO_HIDDEN)?;

                // SHGetFileInfoW();

                tracing::info!("");
                tracing::info!("normal: {:?}", &name);
                tracing::info!("for_parsing: {:?}", &id);

                result.push(DesktopEntry {
                    name,
                    icon: None,
                    command: vec![id],
                });
            }

            Ok(result)
        };

        let result = collect_fn();

        CoUninitialize();

        result
    }
}

pub fn spawn_detached(app_id: &str) -> anyhow::Result<()> {

    // different kinds of app ids
    // 1. Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe!App
    // 2. {F38BF404-1D43-42F2-9305-67DE0B28FC23}\\regedit.exe
    // 3. {7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\\Windows Kits\\10\\Shortcuts\\WindowsStoreAppDevCenterToolsDocumentation.url
    // 4. {1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WF.msc
    // 5. {1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\appverif.chm
    // 6. MSEdge
    // 7. VisualStudio.f7b86bd3
    // 8. Microsoft.Windows.RemoteDesktop
    // 9. Microsoft.AutoGenerated.{C804BBA7-FA5F-CBF7-8B55-2096E5F972CB} - Resource Monitor
    // 10. Blend.f7b86bd3
    // 11. https://nodejs.org/ - Node.js website

    // SAFETY: no idea, I hope somebody reviews this
    unsafe {
        let hresult = CoInitializeEx(None, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
        if hresult != S_OK {
            return Err(anyhow!("CoInitializeEx {:X}", hresult.0));
        }

        let collect_fn = || {
            let apps_folder = SHGetKnownFolderItem::<_, IShellItem2>(&FOLDERID_AppsFolder, KF_FLAG_DEFAULT, None)
                .map_err(|err| anyhow!("SHGetKnownFolderItem {}", err))?;

            let shell_folder = apps_folder.BindToHandler::<_, IShellFolder2>(None, &BHID_SFObject)
                .map_err(|err| anyhow!("BindToHandler {}", err))?;

            let mut enum_items: Option<IEnumIDList> = None;

            let hresult = shell_folder.EnumObjects(None, SHCONTF_NONFOLDERS.0 as u32, &mut enum_items);
            if hresult != S_OK {
                return Err(anyhow!("EnumObjects {:X}", hresult.0));
            }

            let enum_items = enum_items.ok_or(anyhow!("EnumObjects None"))?;

            let mut items: [*mut ITEMIDLIST; 1] = [&mut ITEMIDLIST::default()];

            loop {
                let hresult = enum_items.Next(&mut items, None);
                if hresult == S_FALSE {
                    break;
                }

                if hresult != S_OK {
                    return Err(anyhow!("Next {:X}", hresult.0));
                }

                let [item] = items;

                let id = get_display_name(&shell_folder, item, SHGDNF(SHGDN_FORPARSING.0 | SHGDN_INFOLDER.0))?
                    .into_string()
                    .unwrap();

                if app_id == id {
                    let context_menu = shell_folder.GetUIObjectOf::<_, IContextMenu>(None, &[item], None)
                        .map_err(|err| anyhow!("GetUIObjectOf {}", err))?;

                    let info = CMINVOKECOMMANDINFO {
                        cbSize: size_of::<CMINVOKECOMMANDINFO>() as _,
                        lpVerb: s!("Open"),
                        nShow: SW_SHOW.0,
                        ..Default::default()
                    };

                    // InvokeCommand The parameter is incorrect
                    context_menu.InvokeCommand(&info)
                        .map_err(|err| anyhow!("InvokeCommand {}", err))?;

                    break;
                }
            }

            Ok(())
        };

        let result = collect_fn();

        // &HSTRING::from(app_id)

        // let aam: IApplicationActivationManager = CoCreateInstance(&ApplicationActivationManager, None, CLSCTX_ALL)?;
        //
        // aam.ActivateApplication(&HSTRING::from(app_id), None, AO_NONE)
        //     .map_err(|err| anyhow!("ActivateApplication {}", err))?;

        // let mut pexecinfo = SHELLEXECUTEINFOW {
        //     cbSize: size_of::<SHELLEXECUTEINFOW>() as _,
        //     fMask: SEE_MASK_IDLIST,
        //     lpVerb: w!("open"),
        //     lpFile: PCWSTR(app_id.as_ptr()),
        //     nShow: SW_SHOW.0,
        //     ..Default::default()
        // };

        // let result = ShellExecuteExW(&mut pexecinfo)
        //     .map_err(|err| anyhow!("ShellExecuteExW {:X}", err.code().0));

        CoUninitialize();

        result
    }
}

unsafe fn get_display_name(
    shell_folder: &IShellFolder,
    item: *mut ITEMIDLIST,
    flags: SHGDNF,
) -> anyhow::Result<OsString> {
    let mut strret = MaybeUninit::<STRRET>::uninit();
    shell_folder.GetDisplayNameOf(item, flags, strret.as_mut_ptr())
        .map_err(|err| anyhow!("GetDisplayNameOf {}", err))?;
    let mut strret = strret.assume_init();

    let mut pwstr = MaybeUninit::<PWSTR>::uninit();
    StrRetToStrW(&mut strret as *mut _, Some(item), pwstr.as_mut_ptr())
        .map_err(|err| anyhow!("StrRetToStrW {}", err))?;
    let pwstr = pwstr.assume_init();

    Ok(wstr_to_os_string(pwstr))
}

unsafe fn wstr_to_os_string(wstr: PWSTR) -> OsString {
    let len = (0..).take_while(|&i| *wstr.0.offset(i) != 0).count();
    let wstr_slice = std::slice::from_raw_parts(wstr.0, len);
    OsString::from_wide(wstr_slice)
}

unsafe fn get_attribute(shell_folder: &IShellFolder, item: *mut ITEMIDLIST, mut attributes: SFGAO_FLAGS) -> anyhow::Result<u32> {
    let mut in_n_out = &mut attributes.0 as *mut _;
    shell_folder.GetAttributesOf(&[item], in_n_out)
        .map_err(|err| anyhow!("GetAttributesOf {}", err))?;

    Ok(*in_n_out)
}