@startuml

'https://www.planttext.com/

== Frontend: Start ==

Frontend -> Server: list of views and commands request
Server --> Frontend: list of views and commands response

== Frontend: Initial View Render ==

Frontend -> Server: open-view event
Server -> Frontend: render components request
Frontend --> Server: render components response

== Frontend: Command Execution ==

Frontend -> Server: execute command

== Frontend: View Update On Event ==

Frontend -> Server: button click, key press in input component, etc
Server -> Frontend: render components request
Frontend --> Server: render components response

== Settings ==

Settings -> Server: request
Server --> Settings: response

@enduml